import React from "react";
import "./globals.css";

// This is an example for static MetaData added to a specific page
export const metadata = {
	title: "Next.js 13 + App Router Starter",
	description: "Generated by create next app and tweaked by Spas Z. Spasov",
};

interface RootLayoutProps {
	children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
	return children;
}
